# Generated by Django 5.0.2 on 2024-02-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_headline_date_headline_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
